nav:
  - About: /
  - Buy ClyphX Pro: https://isotonikstudios.com/product/clyphx-pro/
  - Setup: setup
  - Core Concepts: core-concepts
  - Action Reference: action-reference
  - Optional Accessories: optional-accessories