nav:
  - About: /
  - Buy ClyphX Pro: https://isotonikstudios.com/product/clyphx-pro/
  - Setup: setup
  - Core Concepts: core-concepts
  - Action Reference: action-reference
  - General Action Informaton: general-action-information
  - Addendum: addendum
  - Using MIDI Controllers: using-midi-controllers
  - Optional Accessories: optional-accessories